# controller_frequency: 5.0
recovery_behavior_enabled: true
clearing_rotation_allowed: true

TrajectoryPlannerROS:
   max_vel_x: 0.6
   min_vel_x: 0.2 # X 方向最小速速
   max_vel_y: 0.0  # zero for a differential drive robot
   min_vel_y: 0.0
   max_vel_theta: 2.0
   min_vel_theta: -2.0
   min_in_place_vel_theta: 0.4
   escape_vel: -0.1
   acc_lim_x: 1.5
   acc_lim_y: 0.0  # zero for a differential drive robot
   acc_lim_theta: 1.2

   holonomic_robot: false

   # Goal Tolerance Parameters，目标公差
   yaw_goal_tolerance: 0.3 # about 6 degrees
   xy_goal_tolerance: 0.3  # 5 cm
   latch_xy_goal_tolerance: false
   pdist_scale: 0.4
   gdist_scale: 0.8
   meter_scoring: true

   heading_lookahead: 0.325
   heading_scoring: false
   heading_scoring_timestep: 0.8
   occdist_scale: 0.05
   oscillation_reset_dist: 0.05
   publish_cost_grid_pc: false
   prune_plan: true

   #如果全局规划和本地规划晃动过大，设置sim——time大一点
   # Forward Simulation Parameters，前进模拟参数
   sim_time: 5.0
   sim_granularity: 0.05
   angular_sim_granularity: 0.1
   vx_samples: 18
   vy_samples: 0  # zero for a differential drive robot
   vtheta_samples: 20
   dwa: true
   simple_attractor: false

